######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 29 17:13:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Socket.h
SOURCES += server.cpp Socket.cpp
